FROM nginx
#RUN rm /etc/nginx/conf.d/default.conf
#COPY default.conf /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf
COPY my-site.crt /etc/ssl/certs/my-site.crt
COPY my-site.rsa /etc/ssl/private/my-site.rsa 

#CMD ["nginx", "-g", "daemon off;"]
